name: Workflow Steps Integration Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**' # Run Validate Build on all PR branches
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  workflow-steps-integration-tests:
    name: Run workflow steps integration tests, using keria:${{ matrix.keria-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        keria-version: ['0.2.0-dev3']
        node-version: ['20']
    env:
      KERIA_IMAGE_TAG: ${{ matrix.keria-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm set registry https://registry.npmjs.org/
          npm ci

      - name: Run docker
        run: |
          docker pull weboftrust/keria:${{ matrix.keria-version }}
          # docker compose down -v
          # docker compose up verify -d --pull always

      - name: Build
        run: npm run build

      - name: Run workflow
        run: npx jest -- --runInBand --watchAll=false --runTestsByPath ./test/integration/workflow-steps.test.ts
        # run: npx jest ./test/run-workflow-bank.test.ts -- --bank-num "1" --max-report-size "0" --clean "false" --keria-start-port "3900"
        # run: npx jest ./test/run-workflow-bank.test.ts --testNamePattern api-verifier-bank-test-workflow -- --bank-num "1" --max-report-size "0" --clean "false" --keria-start-port "3900"
